# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4

    # working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python -m venv virtualenv
          #  .source ./virtualenv/bin/activate
            pip install flake8 pytest pytest-cov
          #  pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator