version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/PYTHON_TEST

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |   
            python3 -m venv venv 
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |  
            pytest -v --cov=calculator