version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/PYTHON_TEST

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |   
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |  
            pytest -v --cov=calculator